### ISSUE TITLE
24H2 Updated Method

### ISSUE THREAD

**Issue by WildByDesign** [LesFerch/SwitchExplorer#2]
The tool stopped working on 24H2 a few months ago after an update.

However, an updated method to bring back old Explorer on 24H2 was just discovered within the past 7 days.

Source: https://www.neowin.net/amp/how-to-permanently-restore-old-file-explorer-in-windows-11/

I have tested this with the latest 24H2 updates and it works perfectly.

**Comment by LesFerch** [comment]
Version 2.0.0 included a version check that caused it to stop with a message if it was running on an Insider build. Version 2.0.1 removed that check so it now only checks that you're running Windows 11. Version 2.0.2 is the same, except that the exe is also digitally signed.

The method in the neowin article is _exactly_ the same method used by SwitchExplorer.

Please try the current version (2.0.2). It should work fine.

**Comment by WildByDesign** [comment]
Sorry about that, I may have neglected to update to the previous version. I will try that later in the day and get back to you here.

**Comment by LesFerch** [comment]
Also note that accurate credit for the method is included in the SwitchExplorer readme.

**Comment by WildByDesign** [comment]
I was foolish and still on version 1.1, so I updated and it works great as you said.

I figured Neowin would have been more up-to-date with their information and sources, but it tricked me.

The documentation for all of your tools is thorough and well documented, including linking to original sources. Much respect, Les. Cheers!
