### ISSUE TITLE
[BUG] Sometimes explorer will show an addition toolbar when I switch back to Win11 explorer

### ISSUE THREAD

**Issue by GF-Huang** [LesFerch/SwitchExplorer#4]
![image](https://github.com/user-attachments/assets/d706f7c0-2a93-4091-9be7-03062186bfbd)

**Comment by LesFerch** [comment]
It's not really a bug in SwitcherExplorer, but just a registry setting that affects dark mode. Set this to fix it:

```
[HKEY_CURRENT_USER\SOFTWARE\Microsoft\Internet Explorer\Toolbar]
"Locked"=dword:00000001
```
Assuming there's no downside, I'll update SwitchExplorer to add that setting.

For reference see this [Reddit thread](https://www.reddit.com/r/WindowsHelp/comments/1gt12h3/comment/lxiuk57/).

**Comment by GF-Huang** [comment]
Can I remove `[HKEY_CURRENT_USER\SOFTWARE\Microsoft\Internet Explorer\Toolbar]` directly?

**Comment by LesFerch** [comment]
I think you have to set the "locked" value to 1. I'll check when I'm back at my computer.

**Comment by GF-Huang** [comment]
I had check the source, when switch to Win10, it set value to `ITBar7Layout`. But I can't found any code about delete it while switch back to Win11. So I doubt it needs to be deleted.

https://github.com/LesFerch/SwitchExplorer/blob/6b8b1964776f84a8d4114d8cf2f853d017caac1f/Program.cs#L281-L283

**Comment by LesFerch** [comment]
The `ITBar7Layout` setting changes one byte to `1` so that the Windows 10 Explorer remembers its windows size and position. That byte does not need to be changed back to `0` for the Windows 11 Explorer. I don't think the `ITBar7Layout` registry entry is related to the issue.

What is your current setting for the `Locked` dword value within the key `HKCU\Software\Microsoft\Internet Explorer\Toolbar`?

If it's currently `0`, set it to `1` and see if that clears up the problem.

**Comment by GF-Huang** [comment]
The toolbar randomly appear, so I can't be sure is it works.

**Comment by LesFerch** [comment]
Yes, I have researched this issue and have concluded that it's an intermittent Windows 11 Explorer bug that many other people, who have not used SwitchExplorer, have experienced. I'll add code to explicitly set that toolbar "locked" value to 1 as it may help and can't hurt. There's also an explorer setting named "AlwaysShowMenus" that appears to have no effect in Windows 11, but I'll set it to 0 anyhow.

**Comment by LesFerch** [comment]
Version 2.0.3 includes those registry settings and is now available to download.
